Arm:
  ArmDisarm:
    skip: false

Telemetry:
  sim_factor: 1
  HaveHeartbeat:
    skip: false
    minimal_rate: 1
  HaveBatteryStatus:
    skip: false
    minimal_rate: 1
  HaveSysStatus:
    skip: false
    minimal_rate: 1
  HaveExtendedSysStatus:
    skip: false
    minimal_rate: 1
  HaveGPSRaw:
    skip: false
    minimal_rate: 5
  HaveGlobalPosition:
    skip: true
    minimal_rate: 5
  HaveAltitude:
    skip: false
    minimal_rate: 5
  HaveAttitude:
    skip: false
    minimal_rate: 15
  HaveEstimatorStatus:
    skip: false
    minimal_rate: 1

Mission:
  home_lat: 45.4671160
  home_lon: -73.7578370

  Capabilities:
    skip: false
  Upload:
    skip: false
  UploadAndDownload:
    skip: false
  UploadTakeoffLoiterMission:
    skip: false

MissionSDK:
  UploadDownloadCompare:
    skip: false
  UploadTakeoffLoiterMission:
    skip: false

Command:
  RequestMessage:
    skip: false
  RequestProtocolVersion:
    skip: false
  RequestAutopilotC  UploadTakeoffLoiterMission:
    skip: falseapabilities:
    skip: false
  RequestAltitude:
    skip: false
  RequestPoiReport:
    skip: false
  RequestHomePosition:
    skip: false  UploadTakeoffLoiterMission:
    skip: false
  RequestFlightInformation:
    skip: false
  SetMessageInterval:
    skip: false

