Param:
  ParamReadWriteInteger:
    skip: true
    param_id: SYS_HITL
    default_value: 0
    change_value: 1

  ParamReadWriteFloat:
    skip: true
    param_id: MPC_ACC_DOWN_MAX
    default_value: 10.0
    change_value: 3.0

  ParamListAll:
    skip: true


Telemetry:
  sim_factor: 1
  HaveHeartbeat:
    skip: false
    minimal_rate: 1
  HaveBatteryStatus:
    skip: false
    minimal_rate: 1
  HaveSysStatus:
    skip: false
    minimal_rate: 1
  HaveExtendedSysStatus:
    skip: false
    minimal_rate: 1
  HaveGPSRaw:
    skip: false
    minimal_rate: 5
  HaveGlobalPosition:
    skip: true
    minimal_rate: 5
  HaveAltitude:
    skip: false
    minimal_rate: 5
  HaveAttitude:
    skip: false
    minimal_rate: 15
  HaveEstimatorStatus:
    skip: false
    minimal_rate: 1
  HaveAttitudeQuaternion:
    skip: true
    minimal_rate: 15
  HaveAttitudeTarget:
    skip: true
    minimal_rate: 0
  HaveHomePosition:
    skip: true
    minimal_rate: 0
  HaveLocalPosition:
    skip: true
    minimal_rate: 0
  HavePositionTarget:
    skip: true
    minimal_rate: 0
  HaveVFRHUD:
    skip: true
    minimal_rate: 0

Mission:
  home_lat: 45.4671160
  home_lon: -73.7578370

  Upload:
    skip: false
  UploadAndDownload:
    skip: false
  SetCurrentItem:
    skip: false
  UploadPolygonFence:
    skip: true
  UploadCircularFence:
    skip: true
  UploadRallyPoints:
    skip: true

MissionSDK:
  UploadDownloadCompare:
    skip: false


FTP:
  file_size: 10000
  target_path: "/fs/microsd/"
  UploadCompareDownloadCompare:
    skip: true

Ping:
  PingPong:
    skip: true

Command:
  RequestMessage:
    skip: false
  RequestProtocolVersion:
    skip: false
  RequestAutopilotCapabilities:
    skip: false
